package com.irkop.cell.features.admin

import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import com.irkop.cell.core.UserSession
import com.irkop.cell.data.Repository
import com.irkop.cell.features.common.NativeTextField
import kotlinx.coroutines.launch
import kotlinx.serialization.json.*

private fun JsonObject.s(vararg k:String)=k.firstNotNullOfOrNull{this[it]?.jsonPrimitive?.contentOrNull?.takeIf(String::isNotBlank)}?:"-"
private fun JsonObject.n(vararg k:String)=k.firstNotNullOfOrNull{this[it]?.jsonPrimitive?.longOrNull}?:0L
private fun JsonObject.a(k:String)=this[k]?.jsonArray?.filterIsInstance<JsonObject>()?:emptyList()

@Composable fun OperationsScreen(user:UserSession,repo:Repository){
 var tab by remember{mutableStateOf("produk")};val tabs=listOf("produk" to "Produk","kategori" to "Kategori","pengeluaran" to "Pengeluaran","gaji" to "Gaji","settings" to "Pengaturan","logs" to "Audit","notifhook" to "NotifHook")
 Column(Modifier.fillMaxSize().padding(10.dp)){Row(horizontalArrangement=Arrangement.spacedBy(5.dp)){tabs.forEach{(k,v)->FilterChip(tab==k,{tab=k},label={Text(v)})}};Spacer(Modifier.height(8.dp));when(tab){"produk"->ProductTab(repo);"kategori"->CategoryTab(repo);"pengeluaran"->ExpenseTab(repo);"gaji"->SalaryTab(repo);"settings"->SettingsTab(repo);"logs"->AuditTab(repo);"notifhook"->NotifHookTab(repo)}}
}
@Composable private fun ProductTab(repo:Repository){var rows by remember{mutableStateOf(emptyList<JsonObject>())};var q by remember{mutableStateOf("")};var edit by remember{mutableStateOf<JsonObject?>(null)};var add by remember{mutableStateOf(false)};var error by remember{mutableStateOf<String?>(null)};val scope=rememberCoroutineScope();fun load(){scope.launch{runCatching{repo.produk()}.onSuccess{rows=it.a("items")}.onFailure{error=it.message}}};LaunchedEffect(Unit){load()};val shown=rows.filter{q.isBlank()||it.s("nama","sku").contains(q,true)||it.s("kategori_nama").contains(q,true)};Column(verticalArrangement=Arrangement.spacedBy(6.dp)){Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Text("Produk",style=MaterialTheme.typography.titleLarge);Button({add=true}){Text("Tambah")}};NativeTextField(q,{q=it},"Cari produk");Button(::load){Text("Refresh")};error?.let{Text(it,color=MaterialTheme.colorScheme.error)};LazyColumn{items(shown){r->Card(Modifier.fillMaxWidth()){Column(Modifier.padding(8.dp)){Text(r.s("nama"));Text("SKU ${r.s("sku")} · ${r.s("kategori_nama")}");Text("Jual ${r.n("harga_jual","harga")} · Modal ${r.n("harga_modal","modal")} · Stok ${r.n("stok")} · Min ${r.n("stok_minimum")}");TextButton({edit=r}){Text("Edit")}}}}}};if(add)ProductForm(repo,null,{add=false;load()},{add=false});edit?.let{ProductForm(repo,it,{edit=null;load()},{edit=null})}}
@Composable private fun ProductForm(repo:Repository,row:JsonObject?,done:()->Unit,cancel:()->Unit){var name by remember(row){mutableStateOf(row?.s("nama").takeUnless{it=="-"}?:"")};var sku by remember(row){mutableStateOf(row?.s("sku").takeUnless{it=="-"}?:"")};var price by remember(row){mutableStateOf(row?.s("harga_jual").takeUnless{it=="-"}?:"")};var cost by remember(row){mutableStateOf(row?.s("harga_modal").takeUnless{it=="-"}?:"")};var unit by remember(row){mutableStateOf(row?.s("satuan").takeUnless{it=="-"}?:"pcs")};var stock by remember(row){mutableStateOf(row?.s("stok").takeUnless{it=="-"}?:"0")};var min by remember(row){mutableStateOf(row?.s("stok_minimum").takeUnless{it=="-"}?:"0")};var err by remember{mutableStateOf<String?>(null)};val scope=rememberCoroutineScope();AlertDialog(onDismissRequest=cancel,title={Text(if(row==null)"Tambah Produk" else "Edit Produk")},text={Column(verticalArrangement=Arrangement.spacedBy(5.dp)){NativeTextField(name,{name=it},"Nama");NativeTextField(sku,{sku=it},"SKU");NativeTextField(price,{price=it},"Harga jual",numeric=true);NativeTextField(cost,{cost=it},"Harga modal",numeric=true);NativeTextField(unit,{unit=it},"Satuan");NativeTextField(stock,{stock=it},"Stok",numeric=true);NativeTextField(min,{min=it},"Stok minimum",numeric=true);err?.let{Text(it,color=MaterialTheme.colorScheme.error)}}},confirmButton={Button({scope.launch{runCatching{buildJsonObject{put("nama",name.trim());put("sku",sku.trim());price.toLongOrNull()?.let{put("harga_jual",it)};cost.toLongOrNull()?.let{put("harga_modal",it)};put("satuan",unit.trim());stock.toLongOrNull()?.let{put("stok",it)};min.toLongOrNull()?.let{put("stok_minimum",it)}}.let{if(row==null)repo.createProduk(it)else repo.updateProduk(row.s("id"),it)}}.onSuccess{done()}.onFailure{err=it.message}}}){Text("Simpan")}},dismissButton={TextButton(cancel){Text("Batal")}})}
@Composable private fun CategoryTab(repo:Repository){var rows by remember{mutableStateOf(emptyList<JsonObject>())};var name by remember{mutableStateOf("")};var error by remember{mutableStateOf<String?>(null)};val scope=rememberCoroutineScope();fun load(){scope.launch{runCatching{repo.kategori()}.onSuccess{rows=it.a("items")}.onFailure{error=it.message}}};LaunchedEffect(Unit){load()};Column(verticalArrangement=Arrangement.spacedBy(6.dp)){Text("Kategori",style=MaterialTheme.typography.titleLarge);Row{NativeTextField(name,{name=it},"Nama kategori",Modifier.weight(1f));Button({scope.launch{runCatching{repo.createKategori(buildJsonObject{put("nama",name.trim())})}.onSuccess{name="";load()}.onFailure{error=it.message}}}){Text("Tambah")}};error?.let{Text(it,color=MaterialTheme.colorScheme.error)};LazyColumn{items(rows){r->Text("• ${r.s("nama")}",Modifier.padding(5.dp))}}}}
@Composable private fun ExpenseTab(repo:Repository){var rows by remember{mutableStateOf(emptyList<JsonObject>())};var add by remember{mutableStateOf(false)};var edit by remember{mutableStateOf<JsonObject?>(null)};var error by remember{mutableStateOf<String?>(null)};val scope=rememberCoroutineScope();fun load(){scope.launch{runCatching{repo.pengeluaran()}.onSuccess{rows=it.a("items")}.onFailure{error=it.message}}};LaunchedEffect(Unit){load()};Column{Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Text("Pengeluaran",style=MaterialTheme.typography.titleLarge);Button({add=true}){Text("Tambah")}};Button(::load){Text("Refresh")};error?.let{Text(it,color=MaterialTheme.colorScheme.error)};LazyColumn{items(rows){r->Card(Modifier.fillMaxWidth()){Column(Modifier.padding(8.dp)){Text(r.s("deskripsi"));Text("${r.n("nominal")} · ${r.s("metode_bayar")} · ${r.s("akun_sumber")}");TextButton({edit=r}){Text("Edit")}}}}}};if(add)ExpenseForm(repo,null,{add=false;load()},{add=false});edit?.let{ExpenseForm(repo,it,{edit=null;load()},{edit=null})}}
@Composable private fun ExpenseForm(repo:Repository,row:JsonObject?,done:()->Unit,cancel:()->Unit){var desc by remember(row){mutableStateOf(row?.s("deskripsi").takeUnless{it=="-"}?:"")};var amount by remember(row){mutableStateOf(row?.s("nominal").takeUnless{it=="-"}?:"")};var method by remember(row){mutableStateOf(row?.s("metode_bayar").takeUnless{it=="-"}?:"tunai")};var account by remember(row){mutableStateOf(row?.s("akun_sumber").takeUnless{it=="-"}?:"")};var date by remember(row){mutableStateOf(row?.s("tanggal").takeUnless{it=="-"}?:"")};var err by remember{mutableStateOf<String?>(null)};val scope=rememberCoroutineScope();AlertDialog(onDismissRequest=cancel,title={Text(if(row==null)"Tambah Pengeluaran" else "Edit Pengeluaran")},text={Column(verticalArrangement=Arrangement.spacedBy(5.dp)){NativeTextField(desc,{desc=it},"Deskripsi");NativeTextField(amount,{amount=it},"Nominal",numeric=true);NativeTextField(method,{method=it},"Metode: tunai/transfer");NativeTextField(account,{account=it},"Akun sumber");NativeTextField(date,{date=it},"Tanggal YYYY-MM-DD");err?.let{Text(it,color=MaterialTheme.colorScheme.error)}}},confirmButton={Button({scope.launch{runCatching{buildJsonObject{put("deskripsi",desc.trim());put("nominal",amount.toLong());put("metode_bayar",method.trim());put("akun_sumber",account.trim());if(date.isNotBlank())put("tanggal",date)}.let{if(row==null)repo.createPengeluaran(it)else repo.updatePengeluaran(row.s("id"),it)}}.onSuccess{done()}.onFailure{err=it.message}}}){Text("Simpan")}},dismissButton={TextButton(cancel){Text("Batal")}})}
@Composable private fun SalaryTab(repo:Repository){var rows by remember{mutableStateOf(emptyList<JsonObject>())};var add by remember{mutableStateOf(false)};var error by remember{mutableStateOf<String?>(null)};val scope=rememberCoroutineScope();fun load(){scope.launch{runCatching{repo.gaji()}.onSuccess{rows=it.a("items")}.onFailure{error=it.message}}};LaunchedEffect(Unit){load()};Column{Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Text("Gaji Karyawan",style=MaterialTheme.typography.titleLarge);Button({add=true}){Text("Input")}};error?.let{Text(it,color=MaterialTheme.colorScheme.error)};LazyColumn{items(rows){r->Text("${r.s("karyawan_nama","nama")} · ${r.n("nominal","gaji")} · ${r.s("tanggal")} · ${r.s("sumber")}",Modifier.padding(5.dp))}}};if(add)SalaryForm(repo,{add=false;load()},{add=false})}
@Composable private fun SalaryForm(repo:Repository,done:()->Unit,cancel:()->Unit){var user by remember{mutableStateOf("")};var amount by remember{mutableStateOf("")};var date by remember{mutableStateOf("")};val scope=rememberCoroutineScope();AlertDialog(onDismissRequest=cancel,title={Text("Input Gaji")},text={Column{NativeTextField(user,{user=it},"Karyawan ID",numeric=true);NativeTextField(amount,{amount=it},"Nominal",numeric=true);NativeTextField(date,{date=it},"Tanggal YYYY-MM-DD")}},confirmButton={Button({scope.launch{runCatching{repo.createGaji(buildJsonObject{put("karyawan_id",user.toLong());put("nominal",amount.toLong());if(date.isNotBlank())put("tanggal",date)})}.onSuccess{done()}}}){Text("Simpan")}},dismissButton={TextButton(cancel){Text("Batal")}})}
@Composable private fun SettingsTab(repo:Repository){var data by remember{mutableStateOf<JsonObject?>(null)};var source by remember{mutableStateOf("")};var error by remember{mutableStateOf<String?>(null)};val scope=rememberCoroutineScope();fun load(){scope.launch{runCatching{repo.settings()}.onSuccess{data=it}.onFailure{error=it.message}}};LaunchedEffect(Unit){load()};Column(verticalArrangement=Arrangement.spacedBy(6.dp)){Text("Pengaturan",style=MaterialTheme.typography.titleLarge);Text("Website: ${data?.s("website_name","nama_website")?:"-"}");Text("Tema: ${data?.s("theme","tema")?:"-"}");NativeTextField(source,{source=it},"Sumber NotifHook");Button({scope.launch{runCatching{repo.updateSettings(buildJsonObject{put("website_name",data?.s("website_name","nama_website")?:"")})}.onSuccess{load()}.onFailure{error=it.message}}}){Text("Simpan setting")};Button({scope.launch{runCatching{repo.generateSettings()}.onSuccess{data=it}.onFailure{error=it.message}}}){Text("Generate API key")};Button({scope.launch{runCatching{repo.updateNotifhookSource(buildJsonObject{put("source",source.trim())})}.onSuccess{load()}.onFailure{error=it.message}}}){Text("Simpan sumber NotifHook")};error?.let{Text(it,color=MaterialTheme.colorScheme.error)}}}
@Composable private fun AuditTab(repo:Repository){var rows by remember{mutableStateOf(emptyList<JsonObject>())};var error by remember{mutableStateOf<String?>(null)};val scope=rememberCoroutineScope();fun load(){scope.launch{runCatching{repo.logs()}.onSuccess{rows=it.a("items")}.onFailure{error=it.message}}};LaunchedEffect(Unit){load()};Column{Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Text("Audit Log",style=MaterialTheme.typography.titleLarge);Button(::load){Text("Refresh")}};error?.let{Text(it,color=MaterialTheme.colorScheme.error)};LazyColumn{items(rows){r->Text("${r.s("created_at","timestamp")} · ${r.s("action")} · ${r.s("table_name","table")} · ${r.s("user_nama","username")}",Modifier.padding(5.dp));Text("before=${r.s("data_before")} after=${r.s("data_after")}",Modifier.padding(start=10.dp))}}}}
@Composable private fun NotifHookTab(repo:Repository){var key by remember{mutableStateOf("")};var payload by remember{mutableStateOf("")};var result by remember{mutableStateOf<String?>(null)};val scope=rememberCoroutineScope();Column(verticalArrangement=Arrangement.spacedBy(6.dp)){Text("NotifHook",style=MaterialTheme.typography.titleLarge);NativeTextField(key,{key=it},"X-API-Key");NativeTextField(payload,{payload=it},"Payload JSON");Button({scope.launch{runCatching{repo.notifhook(Json.parseToJsonElement(payload).jsonObject,key)}.onSuccess{result="Webhook berhasil diterima"}.onFailure{result=it.message}}}){Text("Kirim webhook")};result?.let{Text(it)}}}
