package com.irkop.cell

import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.input.PasswordVisualTransformation
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import kotlinx.coroutines.launch
import org.json.JSONArray
import org.json.JSONObject
import java.text.NumberFormat
import java.util.Locale

private val BG=Color(0xFF131313);private val C1=Color(0xFF1B1B1C);private val C2=Color(0xFF202020);private val C3=Color(0xFF2A2A2A);private val FG=Color(0xFFE5E2E1);private val MUTED=Color(0xFFBCC9C5);private val P=Color(0xFF70D8C8);private val OK=Color(0xFF4EDEA3);private val ERR=Color(0xFFFFB4AB);private val ONP=Color(0xFF003731)
private val SCHEME=darkColorScheme(primary=P,onPrimary=ONP,secondary=OK,background=BG,onBackground=FG,surface=BG,onSurface=FG,surfaceVariant=C3,onSurfaceVariant=MUTED,error=ERR)
private enum class Screen{HOME,KASIR,TRANSAKSI,LAPORAN,STOK,SERVICE,KASBON,PELANGGAN,PENGELUARAN,GAJI,PENGATURAN,MORE}
private fun JSONObject.s(vararg k:String)=k.firstOrNull{has(it)&&!isNull(it)}?.let{optString(it)}? : ""
private fun JSONObject.n(vararg k:String)=k.firstOrNull{has(it)&&!isNull(it)}?.let{optLong(it)}?:0L
private fun money(v:Long)=NumberFormat.getCurrencyInstance(Locale("id","ID")).format(v).replace(",00","")
private fun JSONArray.list():List<JSONObject>=buildList{for(i in 0 until length())optJSONObject(i)?.let{add(it)}}

class NativeActivity:ComponentActivity(){override fun onCreate(b:Bundle?){super.onCreate(b);setContent{MaterialTheme(colorScheme=SCHEME){App()}}}}

@Composable private fun App(){val api=remember{ApiClient(LocalContext.current)};var auth by remember{mutableStateOf(api.hasToken())};if(auth)Shell(api){auth=false}else Login(api){auth=true}}
@Composable private fun Login(api:ApiClient,ok:()->Unit){var u by remember{mutableStateOf("")};var p by remember{mutableStateOf("")};var busy by remember{mutableStateOf(false)};var error by remember{mutableStateOf("")};val scope=rememberCoroutineScope();Box(Modifier.fillMaxSize().background(BG).padding(20.dp),contentAlignment=Alignment.Center){Card(Modifier.fillMaxWidth().widthIn(max=440.dp),colors=CardDefaults.cardColors(C1),shape=RoundedCornerShape(30.dp)){Column(Modifier.padding(24.dp),verticalArrangement=Arrangement.spacedBy(14.dp)){Text("Irkop Cell",fontSize=32.sp,fontWeight=FontWeight.ExtraBold);Text("Solusi Kasir, PPOB & Servis Konter Modern",color=MUTED);AssistChip(onClick={},label={Text("FAST SYNC • CLOUD POS")});OutlinedTextField(u,{u=it},Modifier.fillMaxWidth(),label={Text("ID Kasir / Username")},singleLine=true);OutlinedTextField(p,{p=it},Modifier.fillMaxWidth(),label={Text("Kata Sandi / PIN Sesi")},singleLine=true,visualTransformation=PasswordVisualTransformation());if(error.isNotBlank())Text(error,color=ERR);Button({scope.launch{busy=true;try{api.login(u,p);ok()}catch(e:Exception){error=e.message?:"Login gagal"}finally{busy=false}}},enabled=!busy&&u.isNotBlank()&&p.isNotBlank(),Modifier.fillMaxWidth().height(52.dp)){if(busy)CircularProgressIndicator(Modifier.size(20.dp))else Text("Masuk Sesi Kasir",fontWeight=FontWeight.Bold)}}}}}

@Composable private fun Shell(api:ApiClient,logout:()->Unit){var screen by remember{mutableStateOf(Screen.HOME)};var tx by remember{mutableStateOf(false)};Scaffold(containerColor=BG,bottomBar={NavigationBar(containerColor=BG){listOf(Screen.HOME to "Beranda" to Icons.Default.Home,Screen.TRANSAKSI to "Kasir" to Icons.Default.PointOfSale,Screen.LAPORAN to "Laporan" to Icons.Default.Assessment,Screen.MORE to "Lainnya" to Icons.Default.MoreHoriz).forEach{val p=it.first.first;NavigationBarItem(screen==p,{screen=p},{Icon(it.second,null)},label={Text(it.first.second)})}}},floatingActionButton={if(screen in listOf(Screen.HOME,Screen.TRANSAKSI,Screen.LAPORAN))ExtendedFloatingActionButton({tx=true},icon={Icon(Icons.Default.Add,null)},text={Text("Transaksi Baru")},containerColor=P,contentColor=ONP)}){pad->Box(Modifier.fillMaxSize().padding(pad)){when(screen){Screen.HOME->Home(api){screen=it};Screen.KASIR->Cashier(api);Screen.TRANSAKSI->Data(api,"Transaksi","/api/transaksi"){o->"${o.s("id")} • ${o.s("pelanggan_nama").ifBlank{"Umum"}} • ${money(o.n("total"))}"};Screen.LAPORAN->Report(api);Screen.STOK->Data(api,"Daftar Barang & Stok","/api/produk"){o->"${o.s("nama","nama_produk")} • Stok ${o.n("stok")} • ${money(o.n("harga_jual","harga"))}"};Screen.SERVICE->Data(api,"Service HP","/api/service-hp"){o->"${o.s("nama_pelanggan","pelanggan_nama")} • ${o.s("status")} • ${o.s("keluhan","deskripsi")}"};Screen.KASBON->Data(api,"Kasbon","/api/kasbon"){o->"${o.s("pelanggan_nama","nama_pelanggan")} • ${money(o.n("sisa","nominal","jumlah"))} • ${o.s("status")}"};Screen.PELANGGAN->Data(api,"Pelanggan","/api/pelanggan"){o->"${o.s("nama")} • ${o.s("no_hp","telepon","nomor")}"};Screen.PENGELUARAN->Data(api,"Pengeluaran","/api/pengeluaran"){o->"${o.s("deskripsi")} • ${money(o.n("nominal"))}"};Screen.GAJI->Data(api,"Gaji Karyawan","/api/gaji"){o->"${o.s("nama_karyawan","nama")} • ${money(o.n("nominal","jumlah"))}"};Screen.PENGATURAN->Settings(api);Screen.MORE->More({screen=it},logout)}}};if(tx)Tx(api){tx=false}}}

@Composable private fun Top(t:String,sub:String?=null){Column(Modifier.padding(16.dp)){Text(t,fontSize=22.sp,fontWeight=FontWeight.Bold);sub?.let{Text(it,color=MUTED,fontSize=12.sp)}}}
@Composable private fun Home(api:ApiClient,nav:(Screen)->Unit){var d by remember{mutableStateOf<JSONObject?>(null)};LaunchedEffect(Unit){d=runCatching{api.get("/api/kasir/current")}.getOrNull()};LazyColumn(contentPadding=PaddingValues(bottom=100.dp)){item{Top("Irkop Cell","SESI KASIR: ${(d?.s("status")?:"MEMUAT").uppercase()}")};item{Column(Modifier.padding(16.dp)){Text("Selamat datang 👋",color=MUTED);Text("Kelola toko lebih cepat hari ini",fontSize=26.sp,fontWeight=FontWeight.ExtraBold);Spacer(Modifier.height(16.dp));Card(colors=CardDefaults.cardColors(C1),shape=RoundedCornerShape(28.dp)){Column(Modifier.padding(20.dp)){val total=d?.optJSONArray("saldo")?.list()?.sumOf{it.n("saldo_sistem")}?:0;Text("Saldo Sistem",color=MUTED);Text(money(total),fontSize=30.sp,fontWeight=FontWeight.ExtraBold);Text("Data finansial berasal dari backend",color=MUTED,fontSize=12.sp)}};Spacer(Modifier.height(22.dp));Text("Menu Kasir Utama",fontSize=18.sp,fontWeight=FontWeight.Bold);Spacer(Modifier.height(10.dp))}};item{Grid(nav)}}}
@Composable private fun Grid(nav:(Screen)->Unit){val a=listOf("Kasir" to Screen.KASIR,"Transaksi" to Screen.TRANSAKSI,"Laporan" to Screen.LAPORAN,"Produk" to Screen.STOK,"Service" to Screen.SERVICE,"Kasbon" to Screen.KASBON,"Pelanggan" to Screen.PELANGGAN,"Pengeluaran" to Screen.PENGELUARAN);Column{a.chunked(4).forEach{r->Row(Modifier.padding(horizontal=16.dp),horizontalArrangement=Arrangement.spacedBy(8.dp)){r.forEach{(n,p)->Card(Modifier.weight(1f).clickable{nav(p)},colors=CardDefaults.cardColors(C2),shape=RoundedCornerShape(18.dp)){Column(Modifier.fillMaxWidth().padding(12.dp),horizontalAlignment=Alignment.CenterHorizontally){Icon(Icons.Default.Apps,null,tint=P);Text(n,fontSize=10.sp,fontWeight=FontWeight.Bold)}}}};Spacer(Modifier.height(8.dp))}}}

@Composable private fun Cashier(api:ApiClient){var d by remember{mutableStateOf<JSONObject?>(null)};var msg by remember{mutableStateOf("")};var open by remember{mutableStateOf(false)};var close by remember{mutableStateOf(false)};val scope=rememberCoroutineScope();fun load(){scope.launch{try{d=api.get("/api/kasir/current")}catch(e:Exception){msg=e.message?:"Gagal"}}};LaunchedEffect(Unit){load()};val st=d?.s("status")?:"memuat";Column{Top("Kasir & Rekonsiliasi","Sesi harian");if(msg.isNotBlank())Text(msg,color=ERR,modifier=Modifier.padding(16.dp));Card(Modifier.padding(16.dp).fillMaxWidth(),colors=CardDefaults.cardColors(C1),shape=RoundedCornerShape(24.dp)){Column(Modifier.padding(18.dp)){Text("Status",color=MUTED);Text(st.uppercase(),fontSize=24.sp,fontWeight=FontWeight.ExtraBold,color=if(st=="buka")OK else P);d?.optJSONArray("saldo")?.list()?.forEach{Text("${it.s("nama_akun")}: ${money(it.n("saldo_sistem"))}")}}};Row(Modifier.padding(horizontal=16.dp),horizontalArrangement=Arrangement.spacedBy(10.dp)){Button({open=true},enabled=st=="belum_buka"){Text("Buka Kasir")};OutlinedButton({close=true},enabled=st=="buka"){Text("Closing")}}};if(open)CashForm(api,true){open=false;load()};if(close)CashForm(api,false){close=false;load()}}
@Composable private fun CashForm(api:ApiClient,opening:Boolean,done:()->Unit){var v by remember{mutableStateOf("0")};var e by remember{mutableStateOf("")};val scope=rememberCoroutineScope();AlertDialog(onDismissRequest=done,title={Text(if(opening)"Opening Kasir" else "Closing Kasir")},text={Column{Text(if(opening)"Saldo awal Tunai Laci" else "Saldo real Tunai Laci",color=MUTED);OutlinedTextField(v,{v=it.filter(Char::isDigit)},label={Text("Nominal")},singleLine=true);if(e.isNotBlank())Text(e,color=ERR)}},confirmButton={Button({scope.launch{try{if(opening)api.post("/api/kasir/opening",JSONObject().put("saldo_awal",JSONArray().put(JSONObject().put("nama_akun","Tunai Laci").put("saldo",v.toLongOrNull()?:0))),true)else api.post("/api/kasir/closing",JSONObject().put("saldo_real",JSONArray().put(JSONObject().put("nama_akun","Tunai Laci").put("saldo_real",v.toLongOrNull()?:0))),true);done()}catch(x:Exception){e=x.message?:"Gagal"}}}){Text("Simpan")}},dismissButton={TextButton(done){Text("Batal")}})}

@Composable private fun Data(api:ApiClient,title:String,path:String,line:(JSONObject)->String){var rows by remember{mutableStateOf(emptyList<JSONObject>())};var busy by remember{mutableStateOf(true)};var err by remember{mutableStateOf("")};var q by remember{mutableStateOf("")};val scope=rememberCoroutineScope();fun load(){scope.launch{busy=true;try{val d=api.get(path,if(q.isBlank())emptyMap()else mapOf("q" to q));rows=(d.optJSONArray("items")?:d.optJSONArray("data")?:d.optJSONArray("results"))?.list()?:emptyList()}catch(e:Exception){err=e.message?:"Gagal"}finally{busy=false}}};LaunchedEffect(Unit){load()};Column{Top(title,"Data live dari backend");Row(Modifier.padding(horizontal=16.dp)){OutlinedTextField(q,{q=it},Modifier.weight(1f),label={Text("Cari")},singleLine=true);IconButton({load()}){Icon(Icons.Default.Search,null)}};if(err.isNotBlank())Text(err,color=ERR,modifier=Modifier.padding(16.dp));if(busy)Box(Modifier.fillMaxSize(),contentAlignment=Alignment.Center){CircularProgressIndicator()}else LazyColumn(contentPadding=PaddingValues(16.dp),verticalArrangement=Arrangement.spacedBy(8.dp)){if(rows.isEmpty())item{Text("Belum ada data",color=MUTED,modifier=Modifier.padding(30.dp))};items(rows){o->Card(Modifier.fillMaxWidth(),colors=CardDefaults.cardColors(C2),shape=RoundedCornerShape(18.dp)){Column(Modifier.padding(16.dp)){Text(line(o),fontWeight=FontWeight.SemiBold);Text(o.s("id","created_at","tanggal"),color=MUTED,fontSize=11.sp)}}}}}}

@Composable private fun Report(api:ApiClient){var d by remember{mutableStateOf<JSONObject?>(null)};LaunchedEffect(Unit){d=runCatching{api.get("/api/laporan/bulan",mapOf("bulan" to java.time.LocalDate.now().toString().substring(0,7)))}.getOrNull()};Column{Top("Laporan Hari Ini","Ringkasan bulan berjalan dari backend");LazyColumn(contentPadding=PaddingValues(16.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){item{Stat("Omzet",money(d?.n("omzet","total_omzet")?:0))};item{Stat("Laba",money(d?.n("laba","total_laba")?:0))};item{Stat("Pengeluaran",money(d?.n("pengeluaran","total_pengeluaran")?:0))}}}}
@Composable private fun Stat(a:String,b:String){Card(colors=CardDefaults.cardColors(C2),shape=RoundedCornerShape(20.dp)){Row(Modifier.fillMaxWidth().padding(18.dp),horizontalArrangement=Arrangement.SpaceBetween){Text(a,fontWeight=FontWeight.Bold);Text(b,color=P,fontWeight=FontWeight.ExtraBold)}}}
@Composable private fun Settings(api:ApiClient){var d by remember{mutableStateOf<JSONObject?>(null)};LaunchedEffect(Unit){d=runCatching{api.get("/api/settings")}.getOrNull()};Column{Top("Pengaturan","Akses mengikuti permission backend");LazyColumn(contentPadding=PaddingValues(16.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){item{Stat("Nama Website",d?.s("nama_website","nama").ifBlank{"Irkop Cell"})};item{Stat("NotifHook",if(d?.optBoolean("notifhook_enabled")==true)"Aktif" else "Terkonfigurasi di backend")};item{Stat("Keamanan","JWT + permission granular")}}}}
@Composable private fun More(nav:(Screen)->Unit,logout:()->Unit){Column{Top("Lainnya","Operasional & administrasi");LazyColumn(contentPadding=PaddingValues(16.dp),verticalArrangement=Arrangement.spacedBy(8.dp)){listOf("Pelanggan" to Screen.PELANGGAN,"Kasbon" to Screen.KASBON,"Service HP" to Screen.SERVICE,"Gaji Karyawan" to Screen.GAJI,"Pengaturan" to Screen.PENGATURAN).forEach{(n,p)->item{Card(Modifier.fillMaxWidth().clickable{nav(p)},colors=CardDefaults.cardColors(C2),shape=RoundedCornerShape(18.dp)){Text(n,Modifier.padding(18.dp),fontWeight=FontWeight.Bold)}}};item{Button(logout,Modifier.fillMaxWidth()){Text("Keluar")}}}}}

@OptIn(ExperimentalMaterial3Api::class) @Composable private fun Tx(api:ApiClient,done:()->Unit){var product by remember{mutableStateOf("")};var qty by remember{mutableStateOf("1")};var method by remember{mutableStateOf("tunai")};var err by remember{mutableStateOf("")};val scope=rememberCoroutineScope();ModalBottomSheet(done,containerColor=C3){Column(Modifier.padding(20.dp).navigationBarsPadding(),verticalArrangement=Arrangement.spacedBy(10.dp)){Text("Transaksi Baru",fontSize=24.sp,fontWeight=FontWeight.Bold);OutlinedTextField(product,{product=it},Modifier.fillMaxWidth(),label={Text("ID Produk")},singleLine=true);OutlinedTextField(qty,{qty=it.filter(Char::isDigit)},Modifier.fillMaxWidth(),label={Text("Qty")},singleLine=true);Row(horizontalArrangement=Arrangement.spacedBy(6.dp)){listOf("tunai","transfer","bon","cash_tunai").forEach{FilterChip(it==method,{method=it},{Text(it.uppercase())})}};if(err.isNotBlank())Text(err,color=ERR);Button({scope.launch{try{api.post("/api/transaksi",JSONObject().put("items",JSONArray().put(JSONObject().put("produk_id",product.toLong()).put("qty",qty.toIntOrNull()?:1))).put("metode_bayar",method).put("manual_entry",false),true);done()}catch(e:Exception){err=e.message?:"Gagal membuat transaksi"}}},Modifier.fillMaxWidth()){Text("Simpan Transaksi")}}}}
