package com.irkop.cell

import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.horizontalScroll
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.input.PasswordVisualTransformation
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import kotlinx.coroutines.launch
import org.json.JSONArray
import org.json.JSONObject
import java.text.NumberFormat
import java.util.Locale

private val Bg=Color(0xFF131313);private val S1=Color(0xFF1B1B1C);private val S2=Color(0xFF202020);private val S3=Color(0xFF2A2A2A);private val Txt=Color(0xFFE5E2E1);private val Muted=Color(0xFFBCC9C5);private val Primary=Color(0xFF70D8C8);private val Success=Color(0xFF4EDEA3);private val Error=Color(0xFFFFB4AB);private val OnPrimary=Color(0xFF003731)
private val Scheme=darkColorScheme(primary=Primary,onPrimary=OnPrimary,secondary=Success,background=Bg,onBackground=Txt,surface=Bg,onSurface=Txt,surfaceVariant=S3,onSurfaceVariant=Muted,error=Error)
private enum class Screen{HOME,KASIR,TRANSAKSI,LAPORAN,STOK,SERVICE,KASBON,PELANGGAN,PENGELUARAN,GAJI,PENGATURAN,MORE}
private fun JSONObject.str(vararg keys:String):String{for(k in keys)if(has(k)&&!isNull(k))return optString(k);return ""}
private fun JSONObject.num(vararg keys:String):Long{for(k in keys)if(has(k)&&!isNull(k))return optLong(k);return 0L}
private fun JSONArray.objects():List<JSONObject>{val r=mutableListOf<JSONObject>();for(i in 0 until length())optJSONObject(i)?.let{r.add(it)};return r}
private fun money(v:Long)=NumberFormat.getCurrencyInstance(Locale("id","ID")).format(v).replace(",00","")

class NativeActivity:ComponentActivity(){override fun onCreate(state:Bundle?){super.onCreate(state);setContent{MaterialTheme(colorScheme=Scheme){App()}}}}

@Composable private fun App(){val api=remember{ApiClient(androidx.compose.ui.platform.LocalContext.current)};var logged by remember{mutableStateOf(api.hasToken())};if(logged)Shell(api){api.clearToken();logged=false}else Login(api){logged=true}}

@Composable private fun Login(api:ApiClient,done:()->Unit){var user by remember{mutableStateOf("")};var pass by remember{mutableStateOf("")};var busy by remember{mutableStateOf(false)};var error by remember{mutableStateOf("")};val scope=rememberCoroutineScope();Box(Modifier.fillMaxSize().background(Bg).padding(20.dp),Alignment.Center){Card(Modifier.fillMaxWidth().widthIn(max=440.dp),colors=CardDefaults.cardColors(S1),shape=RoundedCornerShape(30.dp)){Column(Modifier.padding(24.dp),verticalArrangement=Arrangement.spacedBy(14.dp)){Text("Irkop Cell",fontSize=32.sp,fontWeight=FontWeight.ExtraBold);Text("Solusi Kasir, PPOB & Servis Konter Modern",color=Muted);AssistChip(onClick={},label={Text("FAST SYNC • CLOUD POS")});OutlinedTextField(user,{user=it},Modifier.fillMaxWidth(),label={Text("ID Kasir / Username")},singleLine=true);OutlinedTextField(pass,{pass=it},Modifier.fillMaxWidth(),label={Text("Kata Sandi / PIN Sesi")},singleLine=true,visualTransformation=PasswordVisualTransformation());if(error.isNotBlank())Text(error,color=Error);Button(onClick={scope.launch{busy=true;error="";try{api.login(user.trim(),pass);done()}catch(e:Exception){error=e.message?:"Login gagal"}finally{busy=false}}},enabled=!busy&&user.isNotBlank()&&pass.isNotBlank(),Modifier.fillMaxWidth().height(52.dp)){if(busy)CircularProgressIndicator(Modifier.size(20.dp))else Text("Masuk Sesi Kasir",fontWeight=FontWeight.Bold)}}}}}

@Composable private fun Shell(api:ApiClient,logout:()->Unit){var screen by remember{mutableStateOf(Screen.HOME)};var tx by remember{mutableStateOf(false)};Scaffold(containerColor=Bg,bottomBar={NavigationBar(containerColor=Bg){listOf(Triple(Screen.HOME,"Beranda",Icons.Default.Home),Triple(Screen.TRANSAKSI,"Kasir",Icons.Default.PointOfSale),Triple(Screen.LAPORAN,"Laporan",Icons.Default.Assessment),Triple(Screen.MORE,"Lainnya",Icons.Default.MoreHoriz)).forEach{(target,label,icon)->NavigationBarItem(selected=screen==target,onClick={screen=target},icon={Icon(icon,null)},label={Text(label)})}}},floatingActionButton={if(screen==Screen.HOME||screen==Screen.TRANSAKSI||screen==Screen.LAPORAN)ExtendedFloatingActionButton(onClick={tx=true},icon={Icon(Icons.Default.Add,null)},text={Text("Transaksi Baru")},containerColor=Primary,contentColor=OnPrimary)}){pad->Box(Modifier.fillMaxSize().padding(pad)){when(screen){Screen.HOME->Home(api){screen=it};Screen.KASIR->Cashier(api);Screen.TRANSAKSI->Data(api,"Transaksi","/api/transaksi"){o->"${o.str("id")} • ${o.str("pelanggan_nama").ifBlank{"Umum"}} • ${money(o.num("total"))}"};Screen.LAPORAN->Report(api);Screen.STOK->Data(api,"Daftar Barang & Stok","/api/produk"){o->"${o.str("nama","nama_produk")} • stok ${o.num("stok")} • ${money(o.num("harga_jual","harga"))}"};Screen.SERVICE->Data(api,"Service HP","/api/service-hp"){o->"${o.str("nama_pelanggan","pelanggan_nama")} • ${o.str("status")}"};Screen.KASBON->Data(api,"Kasbon","/api/kasbon"){o->"${o.str("pelanggan_nama","nama_pelanggan")} • ${money(o.num("sisa","nominal","jumlah"))}"};Screen.PELANGGAN->Data(api,"Pelanggan","/api/pelanggan"){o->"${o.str("nama")} • ${o.str("no_hp","telepon","nomor")}"};Screen.PENGELUARAN->Data(api,"Pengeluaran","/api/pengeluaran"){o->"${o.str("deskripsi")} • ${money(o.num("nominal"))}"};Screen.GAJI->Data(api,"Gaji Karyawan","/api/gaji"){o->"${o.str("nama_karyawan","nama")} • ${money(o.num("nominal","jumlah"))}"};Screen.PENGATURAN->Settings(api);Screen.MORE->More{screen=it}}};if(tx)Transaction(api){tx=false}}}}

@Composable private fun Header(title:String,sub:String?=null){Column(Modifier.padding(16.dp)){Text(title,fontSize=22.sp,fontWeight=FontWeight.Bold);sub?.let{Text(it,color=Muted,fontSize=12.sp)}}}

@Composable private fun Home(api:ApiClient,go:(Screen)->Unit){var d by remember{mutableStateOf<JSONObject?>(null)};LaunchedEffect(Unit){d=runCatching{api.get("/api/kasir/current")}.getOrNull()};val status=(d?.str("status")?:"memuat").uppercase();val quick=listOf("Kasir" to Screen.KASIR,"Transaksi" to Screen.TRANSAKSI,"Laporan" to Screen.LAPORAN,"Produk" to Screen.STOK,"Service" to Screen.SERVICE,"Kasbon" to Screen.KASBON,"Pelanggan" to Screen.PELANGGAN,"Pengeluaran" to Screen.PENGELUARAN);LazyColumn(contentPadding=PaddingValues(bottom=96.dp)){item{Header("Irkop Cell","SESI KASIR: $status")};item{Column(Modifier.padding(16.dp)){Text("Selamat datang 👋",color=Muted);Text("Kelola toko lebih cepat hari ini",fontSize=26.sp,fontWeight=FontWeight.ExtraBold);Spacer(Modifier.height(16.dp));Card(Modifier.fillMaxWidth(),colors=CardDefaults.cardColors(S1),shape=RoundedCornerShape(28.dp)){Column(Modifier.padding(20.dp)){Text("Saldo Sistem",color=Muted);val total=d?.optJSONArray("saldo")?.objects()?.sumOf{it.num("saldo_sistem","saldo")}?:0L;Text(money(total),fontSize=30.sp,fontWeight=FontWeight.ExtraBold);Text("Data finansial berasal dari backend",color=Muted,fontSize=12.sp)}};Spacer(Modifier.height(20.dp));Text("Perlu Perhatian Segera",fontSize=18.sp,fontWeight=FontWeight.Bold);Spacer(Modifier.height(10.dp));Row(Modifier.horizontalScroll(rememberScrollState()),horizontalArrangement=Arrangement.spacedBy(8.dp)){Attention("Stok Menipis","0 produk",Success);Attention("Kasbon Jatuh Tempo","0 pelanggan",Color(0xFFF59E0B));Attention("Servis Berjalan","0 unit",Color(0xFFADC6FF))};Spacer(Modifier.height(20.dp));Text("Menu Kasir Utama",fontSize=18.sp,fontWeight=FontWeight.Bold);Spacer(Modifier.height(10.dp))}};item{Column(Modifier.padding(horizontal=16.dp)){quick.chunked(4).forEach{row->Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(8.dp)){row.forEach{(label,target)->Card(Modifier.weight(1f).clickable{go(target)},colors=CardDefaults.cardColors(S2),shape=RoundedCornerShape(18.dp)){Column(Modifier.fillMaxWidth().padding(12.dp),horizontalAlignment=Alignment.CenterHorizontally){Icon(Icons.Default.Apps,null,tint=Primary);Text(label,fontSize=10.sp,fontWeight=FontWeight.Bold)}}}};Spacer(Modifier.height(8.dp))}}}}
@Composable private fun Attention(t:String,v:String,c:Color){Card(Modifier.width(170.dp),colors=CardDefaults.cardColors(S2),shape=RoundedCornerShape(20.dp)){Column(Modifier.padding(14.dp)){Text(t,fontWeight=FontWeight.Bold,fontSize=13.sp);Text(v,color=c,fontSize=12.sp)}}}

@Composable private fun Cashier(api:ApiClient){var d by remember{mutableStateOf<JSONObject?>(null)};var err by remember{mutableStateOf("")};var opening by remember{mutableStateOf(false)};var closing by remember{mutableStateOf(false)};val scope=rememberCoroutineScope();fun load(){scope.launch{try{d=api.get("/api/kasir/current");err=""}catch(e:Exception){err=e.message?:"Gagal"}}};LaunchedEffect(Unit){load()};val status=d?.str("status")?:"memuat";Column{Header("Kasir & Rekonsiliasi","Sesi harian");if(err.isNotBlank())Text(err,color=Error,Modifier.padding(16.dp));Card(Modifier.padding(16.dp).fillMaxWidth(),colors=CardDefaults.cardColors(S1),shape=RoundedCornerShape(24.dp)){Column(Modifier.padding(18.dp),verticalArrangement=Arrangement.spacedBy(8.dp)){Text("Status",color=Muted);Text(status.uppercase(),fontSize=24.sp,fontWeight=FontWeight.ExtraBold,color=if(status=="buka")Success else Primary);d?.optJSONArray("saldo")?.objects()?.forEach{Text("${it.str("nama_akun")}: ${money(it.num("saldo_sistem","saldo"))}")}}};Row(Modifier.padding(horizontal=16.dp),horizontalArrangement=Arrangement.spacedBy(8.dp)){Button({opening=true},enabled=status=="belum_buka"){Text("Buka Kasir")};OutlinedButton({closing=true},enabled=status=="buka"){Text("Closing")}}};if(opening)CashDialog(api,true){opening=false;load()};if(closing)CashDialog(api,false){closing=false;load()}}
@Composable private fun CashDialog(api:ApiClient,isOpen:Boolean,done:()->Unit){var amount by remember{mutableStateOf("")};var err by remember{mutableStateOf("")};val scope=rememberCoroutineScope();AlertDialog(onDismissRequest=done,title={Text(if(isOpen)"Opening Kasir" else "Closing Kasir")},text={Column{OutlinedTextField(amount,{amount=it.filter(Char::isDigit)},label={Text("Nominal Tunai Laci")},singleLine=true);if(err.isNotBlank())Text(err,color=Error)}},confirmButton={Button(onClick={scope.launch{try{if(isOpen){val body=JSONObject().put("saldo_awal",JSONArray().put(JSONObject().put("nama_akun","Tunai Laci").put("saldo",amount.toLongOrNull()?:0L)));api.post("/api/kasir/opening",body,financial=true)}else{val body=JSONObject().put("saldo_real",JSONArray().put(JSONObject().put("nama_akun","Tunai Laci").put("saldo_real",amount.toLongOrNull()?:0L)));api.post("/api/kasir/closing",body,financial=true)};done()}catch(e:Exception){err=e.message?:"Gagal"}}}){Text("Simpan")}},dismissButton={TextButton(onClick=done){Text("Batal")}})}

@Composable private fun Data(api:ApiClient,title:String,path:String,format:(JSONObject)->String){var rows by remember{mutableStateOf(emptyList<JSONObject>())};var q by remember{mutableStateOf("")};var loading by remember{mutableStateOf(true)};var err by remember{mutableStateOf("")};val scope=rememberCoroutineScope();fun load(){scope.launch{loading=true;try{val d=api.get(path,if(q.isBlank())emptyMap()else mapOf("q" to q));rows=(d.optJSONArray("items")?:d.optJSONArray("data")?:d.optJSONArray("results"))?.objects().orEmpty();err=""}catch(e:Exception){err=e.message?:"Gagal"}finally{loading=false}}};LaunchedEffect(Unit){load()};Column{Header(title,"Data live dari backend");Row(Modifier.padding(horizontal=16.dp),verticalAlignment=Alignment.CenterVertically){OutlinedTextField(q,{q=it},Modifier.weight(1f),label={Text("Cari")},singleLine=true);IconButton({load()}){Icon(Icons.Default.Search,null)}};if(err.isNotBlank())Text(err,color=Error,Modifier.padding(16.dp));if(loading)Box(Modifier.fillMaxSize(),Alignment.Center){CircularProgressIndicator()}else LazyColumn(contentPadding=PaddingValues(16.dp),verticalArrangement=Arrangement.spacedBy(8.dp)){if(rows.isEmpty())item{Text("Belum ada data",color=Muted,Modifier.padding(30.dp))};items(rows){o->Card(Modifier.fillMaxWidth(),colors=CardDefaults.cardColors(S2),shape=RoundedCornerShape(18.dp)){Column(Modifier.padding(16.dp)){Text(format(o),fontWeight=FontWeight.SemiBold);Text(o.str("id","created_at","tanggal"),color=Muted,fontSize=11.sp)}}}}}}

@Composable private fun Report(api:ApiClient){var d by remember{mutableStateOf<JSONObject?>(null)};LaunchedEffect(Unit){d=runCatching{api.get("/api/laporan/bulan",mapOf("bulan" to java.time.LocalDate.now().toString().substring(0,7)))}.getOrNull()};Column{Header("Laporan Hari Ini","Ringkasan laporan dari backend");LazyColumn(contentPadding=PaddingValues(16.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){item{Stat("Omzet",money(d?.num("omzet","total_omzet")?:0L))};item{Stat("Laba",money(d?.num("laba","total_laba")?:0L))};item{Stat("Pengeluaran",money(d?.num("pengeluaran","total_pengeluaran")?:0L))}}}}
@Composable private fun Stat(a:String,b:String){Card(colors=CardDefaults.cardColors(S2),shape=RoundedCornerShape(20.dp)){Row(Modifier.fillMaxWidth().padding(18.dp),horizontalArrangement=Arrangement.SpaceBetween){Text(a,fontWeight=FontWeight.Bold);Text(b,color=Primary,fontWeight=FontWeight.ExtraBold)}}}
@Composable private fun Settings(api:ApiClient){var d by remember{mutableStateOf<JSONObject?>(null)};LaunchedEffect(Unit){d=runCatching{api.get("/api/settings")}.getOrNull()};Column{Header("Pengaturan","Permission mengikuti backend");LazyColumn(contentPadding=PaddingValues(16.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){item{Stat("Nama Website",d?.str("nama_website","nama").orEmpty().ifBlank{"Irkop Cell"})};item{Stat("Sinkronisasi","Cloud POS API")};item{Stat("Keamanan","JWT + permission granular")}}}}
@Composable private fun More(go:(Screen)->Unit){Column{Header("Lainnya","Operasional & administrasi");LazyColumn(contentPadding=PaddingValues(16.dp),verticalArrangement=Arrangement.spacedBy(8.dp)){listOf("Pelanggan" to Screen.PELANGGAN,"Kasbon" to Screen.KASBON,"Service HP" to Screen.SERVICE,"Produk & Stok" to Screen.STOK,"Pengeluaran" to Screen.PENGELUARAN,"Gaji Karyawan" to Screen.GAJI,"Pengaturan" to Screen.PENGATURAN).forEach{(label,target)->item{Card(Modifier.fillMaxWidth().clickable{go(target)},colors=CardDefaults.cardColors(S2),shape=RoundedCornerShape(18.dp)){Row(Modifier.fillMaxWidth().padding(18.dp),verticalAlignment=Alignment.CenterVertically){Icon(Icons.Default.Apps,null,tint=Primary);Spacer(Modifier.width(14.dp));Text(label,Modifier.weight(1f),fontWeight=FontWeight.Bold);Icon(Icons.Default.ChevronRight,null,tint=Muted)}}}}}}}

@Composable private fun Transaction(api:ApiClient,done:()->Unit){var type by remember{mutableStateOf("")};var amount by remember{mutableStateOf("")};var customer by remember{mutableStateOf("")};var error by remember{mutableStateOf("")};val scope=rememberCoroutineScope();ModalBottomSheet(onDismissRequest=done,containerColor=S3,dragHandle={BottomSheetDefaults.DragHandle(color=Primary)}){Column(Modifier.padding(20.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){Text("Transaksi Baru",fontSize=22.sp,fontWeight=FontWeight.Bold);OutlinedTextField(customer,{customer=it},Modifier.fillMaxWidth(),label={Text("Nomor / pelanggan")},singleLine=true);OutlinedTextField(amount,{amount=it.filter(Char::isDigit)},Modifier.fillMaxWidth(),label={Text("Nominal")},singleLine=true);Text("Produk / layanan",fontWeight=FontWeight.Bold);listOf("Pulsa","Data","Token PLN","Kirim Uang").forEach{label->FilterChip(selected=type==label,onClick={type=label},label={Text(label)})};if(error.isNotBlank())Text(error,color=Error);Button(onClick={scope.launch{try{val body=JSONObject().put("items",JSONArray()).put("metode_bayar","Tunai").put("manual_entry",true).put("catatan",if(type.isBlank())"Transaksi manual" else type);api.post("/api/transaksi",body,financial=true);done()}catch(e:ApiException){error=if(e.status==409)"Sesi kasir sudah ditutup. Buka sesi baru terlebih dahulu." else e.message}catch(e:Exception){error=e.message?:"Transaksi gagal"}}},enabled=type.isNotBlank()&&(amount.toLongOrNull()?:0L)>0L,modifier=Modifier.fillMaxWidth()){Text("Simpan Transaksi")};Spacer(Modifier.height(24.dp))}}}
