package com.irkop.cell

import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.BackHandler
import androidx.activity.compose.setContent
import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.AlertDialog
import androidx.compose.material3.Button
import androidx.compose.material3.Card
import androidx.compose.material3.CardDefaults
import androidx.compose.material3.CircularProgressIndicator
import androidx.compose.material3.FloatingActionButton
import androidx.compose.material3.Icon
import androidx.compose.material3.IconButton
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.NavigationBar
import androidx.compose.material3.NavigationBarItem
import androidx.compose.material3.OutlinedButton
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.Scaffold
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.material3.darkColorScheme
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import kotlinx.coroutines.launch
import org.json.JSONArray
import org.json.JSONObject
import java.text.NumberFormat
import java.util.Locale

private val Scheme = darkColorScheme(primary=Color(0xFF70D8C8),onPrimary=Color(0xFF06332E),primaryContainer=Color(0xFF32A192),onPrimaryContainer=Color.White,secondary=Color(0xFF4EDEA3),background=Color(0xFF202020),surface=Color(0xFF292929),surfaceVariant=Color(0xFF383838),onSurface=Color(0xFFF4F7F5),onSurfaceVariant=Color(0xFFD7E0DC),outline=Color(0xFFAAB7B3),error=Color(0xFFFFB4AB))
private val CardColor=Color(0xFF303030)
private val Good=Color(0xFF4EDEA3)
private val Muted=Color(0xFFD7E0DC)
private val Money=NumberFormat.getNumberInstance(Locale("id","ID"))
private enum class Page{HOME,KASIR,TRANSAKSI,LAPORAN,STOK,KATEGORI,SERVICE,KASBON,PELANGGAN,PENGELUARAN,GAJI,LAINNYA,PENGATURAN}
private fun JSONObject.s(vararg k:String)=k.firstNotNullOfOrNull{optString(it).takeIf{v->v.isNotBlank()}}?:"-"
private fun JSONObject.n(vararg k:String)=k.firstNotNullOfOrNull{optString(it).replace(",","").toDoubleOrNull()?.toLong()}?:0L
private fun JSONObject.a(vararg k:String)=k.firstNotNullOfOrNull{optJSONArray(it)}?.let{a->(0 until a.length()).mapNotNull(a::optJSONObject)}?:emptyList()
private fun rp(n:Long)="Rp ${Money.format(n)}"

class NativeActivity:ComponentActivity(){override fun onCreate(b:Bundle?){super.onCreate(b);setContent{MaterialTheme(colorScheme=Scheme){LoginGate()}}}}

@Composable private fun LoginGate(){val c=LocalContext.current;val api=remember(c){ApiClient(c)};val scope=rememberCoroutineScope();var ready by remember{mutableStateOf(false)};var error by remember{mutableStateOf("")};fun login()=scope.launch{error="";runCatching{if(api.hasToken())runCatching{api.me()}.getOrElse{api.login("demo","demodemo")}else api.login("demo","demodemo")}.onSuccess{ready=true}.onFailure{error=it.message?:"Login gagal"}};LaunchedEffect(Unit){login()};if(ready)App(api)else Box(Modifier.fillMaxSize().background(Scheme.background),contentAlignment=Alignment.Center){Column(horizontalAlignment=Alignment.CenterHorizontally,verticalArrangement=Arrangement.spacedBy(12.dp)){Text("Irkop Cell",style=MaterialTheme.typography.headlineLarge,fontWeight=FontWeight.Bold);if(error.isBlank())CircularProgressIndicator()else Button(onClick={login()}){Text("Coba Lagi")};Text(if(error.isBlank())"Menyiapkan sesi kasir…" else error,color=if(error.isBlank())Muted else Scheme.error)}}}

@Composable private fun App(api:ApiClient){var page by remember{mutableStateOf(Page.HOME)};var history by remember{mutableStateOf(emptyList<Page>())};var sheet by remember{mutableStateOf(false)};val role=remember{api.cachedUser()?.optString("role").orEmpty().uppercase()};fun allowed(p:Page)=p!=Page.GAJI||role !in setOf("KARYAWAN","KASIR","CASHIER");fun open(p:Page){if(allowed(p)&&p!=page){history=history+p;page=p}};fun root(p:Page){if(allowed(p)){page=p;history=emptyList()}};fun back(){if(history.isNotEmpty()){page=history.last();history=history.dropLast(1)}else if(page!=Page.HOME)page=Page.HOME};BackHandler{back()};Scaffold(containerColor=Scheme.background,bottomBar={NavigationBar(containerColor=Color(0xFF292929)){NavigationBarItem(selected=page==Page.HOME,onClick={root(Page.HOME)},icon={Icon(Icons.Default.Home,"Beranda")},label={Text("Beranda")});NavigationBarItem(selected=page==Page.KASIR,onClick={root(Page.KASIR)},icon={Icon(Icons.Default.PointOfSale,"Kasir")},label={Text("Kasir")});NavigationBarItem(selected=page==Page.LAPORAN,onClick={root(Page.LAPORAN)},icon={Icon(Icons.Default.Assessment,"Laporan")},label={Text("Laporan")});NavigationBarItem(selected=page==Page.LAINNYA,onClick={root(Page.LAINNYA)},icon={Icon(Icons.Default.MoreHoriz,"Lainnya")},label={Text("Lainnya")})}},floatingActionButton={FloatingActionButton(onClick={sheet=true},containerColor=Scheme.primary,contentColor=Scheme.onPrimary){Icon(Icons.Default.Add,"Transaksi Baru")}}){p->when(page){Page.HOME->Home(p,::open,role);Page.KASIR->Cashier(p,api,::back);Page.TRANSAKSI->Transactions(p,api,::back);Page.LAPORAN->Reports(p,api,::back);Page.KASBON->Kasbon(p,api,::back);Page.GAJI->Payroll(p,api,::back);Page.LAINNYA->More(p,::open,::back,allowed(Page.GAJI));Page.STOK->Unsupported(p,"Stok","Endpoint produk/stok belum ada di kontrak API resmi.",::back);Page.KATEGORI->Unsupported(p,"Kategori","Endpoint kategori belum ada di kontrak API resmi.",::back);Page.SERVICE->Unsupported(p,"Service HP","Endpoint service belum ada di kontrak API resmi.",::back);Page.PELANGGAN->Unsupported(p,"Pelanggan","Endpoint pelanggan belum ada di kontrak API resmi.",::back);Page.PENGELUARAN->Unsupported(p,"Pengeluaran","Endpoint pengeluaran belum ada di kontrak API resmi.",::back);Page.PENGATURAN->Unsupported(p,"Pengaturan","Endpoint pengaturan belum ada di kontrak API resmi.",::back)}};if(sheet)TransactionSheet(api){sheet=false}}

@Composable private fun Header(title:String,sub:String?=null,back:(()->Unit)?=null){Row(Modifier.fillMaxWidth().padding(vertical=8.dp),verticalAlignment=Alignment.CenterVertically){if(back!=null)IconButton(onClick=back){Icon(Icons.Default.ArrowBack,"Kembali")};Column(Modifier.weight(1f)){Text(title,style=MaterialTheme.typography.headlineSmall,fontWeight=FontWeight.Bold);if(!sub.isNullOrBlank())Text(sub,color=Muted)}}}
@Composable private fun CardText(title:String,body:String,onClick:(()->Unit)?=null){val m=Modifier.fillMaxWidth().then(if(onClick!=null)Modifier.clickable(onClick=onClick)else Modifier);Card(m,colors=CardDefaults.cardColors(CardColor),shape=RoundedCornerShape(16.dp)){Column(Modifier.padding(16.dp),verticalArrangement=Arrangement.spacedBy(5.dp)){Text(title,fontWeight=FontWeight.Bold);Text(body,color=Muted)}}}
@Composable private fun Metric(title:String,value:String,modifier:Modifier){Card(modifier,colors=CardDefaults.cardColors(CardColor),shape=RoundedCornerShape(14.dp)){Column(Modifier.padding(10.dp)){Text(title,color=Muted,style=MaterialTheme.typography.labelSmall);Text(value,fontWeight=FontWeight.Bold)}}}
@Composable private fun Quick(label:String,icon:androidx.compose.ui.graphics.vector.ImageVector,modifier:Modifier,click:()->Unit){Card(modifier.clickable(onClick=click),colors=CardDefaults.cardColors(CardColor),shape=RoundedCornerShape(14.dp)){Column(Modifier.fillMaxWidth().padding(vertical=13.dp),horizontalAlignment=Alignment.CenterHorizontally){Icon(icon,null,tint=Scheme.primary);Spacer(Modifier.height(6.dp));Text(label,style=MaterialTheme.typography.labelSmall,fontWeight=FontWeight.Bold)}}}

@Composable private fun Home(p:PaddingValues,open:(Page)->Unit,role:String){LazyColumn(Modifier.fillMaxSize().padding(p),contentPadding=PaddingValues(16.dp,8.dp,16.dp,110.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){item{Row(Modifier.fillMaxWidth(),verticalAlignment=Alignment.CenterVertically){Column(Modifier.weight(1f)){Text("Irkop Cell",style=MaterialTheme.typography.headlineSmall,fontWeight=FontWeight.Bold);Text("Sesi Kasir: Aktif",color=Good,fontWeight=FontWeight.Bold)};Text(role.ifBlank{"KASIR"},color=Scheme.primary,fontWeight=FontWeight.Bold)}};item{CardText("Sesi Kasir","Opening, saldo akun dan rekonsiliasi"){open(Page.KASIR)}};item{Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(8.dp)){Metric("Saldo Kas","—",Modifier.weight(1f));Metric("Omzet Hari Ini","—",Modifier.weight(1f));Metric("Transaksi","—",Modifier.weight(1f))}};item{Text("Menu Kasir Utama",style=MaterialTheme.typography.titleLarge,fontWeight=FontWeight.Bold)};item{Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(8.dp)){Quick("Stok",Icons.Default.Inventory2,Modifier.weight(1f)){open(Page.STOK)};Quick("Kasbon",Icons.Default.ReceiptLong,Modifier.weight(1f)){open(Page.KASBON)};Quick("Pelanggan",Icons.Default.People,Modifier.weight(1f)){open(Page.PELANGGAN)};Quick("Pengeluaran",Icons.Default.Wallet,Modifier.weight(1f)){open(Page.PENGELUARAN)}}};item{Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(8.dp)){Quick("Service",Icons.Default.Build,Modifier.weight(1f)){open(Page.SERVICE)};Quick("Gaji",Icons.Default.Assessment,Modifier.weight(1f)){open(Page.GAJI)};Quick("Laporan",Icons.Default.Assessment,Modifier.weight(1f)){open(Page.LAPORAN)};Quick("Transaksi",Icons.Default.ReceiptLong,Modifier.weight(1f)){open(Page.TRANSAKSI)}}};item{CardText("Backend","Endpoint resmi dipakai untuk data finansial. Modul tanpa kontrak tidak mengirim request fiktif.")}}}

@Composable private fun Cashier(p:PaddingValues,api:ApiClient,back:()->Unit){var data by remember{mutableStateOf<JSONObject?>(null)};var error by remember{mutableStateOf("")};var opening by remember{mutableStateOf(false)};var closing by remember{mutableStateOf(false)};val scope=rememberCoroutineScope();fun load()=scope.launch{runCatching{api.kasirCurrent()}.onSuccess{data=it;error=""}.onFailure{error=it.message?:"Gagal memuat"}};LaunchedEffect(Unit){load()};val accounts=data?.a("saldo","saldo_akun","accounts","akun").orEmpty();LazyColumn(Modifier.fillMaxSize().padding(p),contentPadding=PaddingValues(16.dp,8.dp,16.dp,110.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){item{Header("Kasir & Rekonsiliasi","GET /api/kasir/current",back)};item{CardText("Status Sesi",data?.s("status","state")?.uppercase()?:"MEMUAT")};if(error.isNotBlank())item{CardText("Error",error)};item{Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(8.dp)){Button(Modifier.weight(1f),onClick={opening=true}){Text("Opening")};OutlinedButton(Modifier.weight(1f),onClick={closing=true}){Text("Closing")}}};item{Text("Saldo Akun",style=MaterialTheme.typography.titleLarge,fontWeight=FontWeight.Bold)};if(accounts.isEmpty())item{CardText("Saldo","Belum ada rincian saldo dari server.")};items(accounts){a->Row(Modifier.fillMaxWidth().padding(5.dp),verticalAlignment=Alignment.CenterVertically){Text(a.s("nama_akun","nama","akun"),Modifier.weight(1f));Text(rp(a.n("saldo","saldo_real","nominal")),fontWeight=FontWeight.Bold)}}};if(opening)AccountDialog("Opening Kasir",api,false){opening=false;load()};if(closing)AccountDialog("Closing Kasir",api,true){closing=false;load()}}

@Composable private fun AccountDialog(title:String,api:ApiClient,closing:Boolean,done:()->Unit){var fields by remember{mutableStateOf(listOf("Kas" to "","OrderKuota" to "","DANA" to "","SeaBank" to "","QRIS" to ""))};var note by remember{mutableStateOf("")};var error by remember{mutableStateOf("")};val scope=rememberCoroutineScope();AlertDialog(onDismissRequest=done,title={Text(title)},text={Column(Modifier.verticalScroll(rememberScrollState()),verticalArrangement=Arrangement.spacedBy(7.dp)){fields.forEachIndexed{i,pair->OutlinedTextField(pair.second,{v->fields=fields.toMutableList().also{it[i]=pair.first to v}},label={Text(pair.first)},singleLine=true,modifier=Modifier.fillMaxWidth())};if(closing)OutlinedTextField(note,{note=it},label={Text("Catatan closing")},modifier=Modifier.fillMaxWidth());if(error.isNotBlank())Text(error,color=Scheme.error)}},confirmButton={Button(onClick={scope.launch{val arr=JSONArray();fields.forEach{(name,value)->arr.put(JSONObject().put("nama_akun",name).put(if(closing)"saldo_real" else "saldo",value.toLongOrNull()?:0L))};runCatching{if(closing)api.kasirClosing(arr,note)else api.kasirOpening(arr)}.onSuccess{done()}.onFailure{error=it.message?:"Gagal menyimpan"}}}){Text("Simpan")}},dismissButton={TextButton(onClick=done){Text("Batal")}})}

@Composable private fun Transactions(p:PaddingValues,api:ApiClient,back:()->Unit){var rows by remember{mutableStateOf(emptyList<JSONObject>())};var date by remember{mutableStateOf("")};var error by remember{mutableStateOf("")};val scope=rememberCoroutineScope();fun load()=scope.launch{runCatching{api.transaksi(if(date.isBlank())emptyMap()else mapOf("date" to date,"limit" to "100"))}.onSuccess{rows=it.a("items","data","transaksi","results");error=""}.onFailure{error=it.message?:"Gagal memuat"}};LaunchedEffect(Unit){load()};LazyColumn(Modifier.fillMaxSize().padding(p),contentPadding=PaddingValues(16.dp,8.dp,16.dp,110.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){item{Header("Transaksi","GET /api/transaksi",back)};item{OutlinedTextField(date,{date=it},label={Text("Tanggal YYYY-MM-DD")},singleLine=true,modifier=Modifier.fillMaxWidth(),trailingIcon={IconButton(onClick={load()}){Icon(Icons.Default.Refresh,"Muat")}})};if(error.isNotBlank())item{CardText("Error",error)};if(rows.isEmpty()&&error.isBlank())item{CardText("Belum ada data","Tidak ada transaksi pada filter ini.")};items(rows){t->TransactionCard(t,api){load()}}}}
@Composable private fun TransactionCard(t:JSONObject,api:ApiClient,changed:()->Unit){var confirm by remember{mutableStateOf(false)};val scope=rememberCoroutineScope();val id=t.s("id","transaksi_id");Card(colors=CardDefaults.cardColors(CardColor),shape=RoundedCornerShape(16.dp)){Row(Modifier.fillMaxWidth().padding(14.dp),verticalAlignment=Alignment.CenterVertically){Column(Modifier.weight(1f)){Text(t.s("nomor","kode","invoice","id"),fontWeight=FontWeight.Bold);Text(t.s("metode_bayar","metode","payment_method"),color=Muted);Text(rp(t.n("total","nominal","grand_total")),color=Good,fontWeight=FontWeight.Bold)};IconButton(onClick={confirm=true}){Icon(Icons.Default.Delete,"Hapus")}}};if(confirm)AlertDialog(onDismissRequest={confirm=false},title={Text("Hapus transaksi?")},text={Text("Transaksi akan di-soft-delete dan mutasi dibalik oleh backend.")},confirmButton={Button(onClick={scope.launch{runCatching{api.deleteTransaksi(id,"Dihapus dari aplikasi")}.onSuccess{changed()}};confirm=false}){Text("Hapus")}},dismissButton={TextButton(onClick={confirm=false}){Text("Batal")}})}

@Composable private fun Reports(p:PaddingValues,api:ApiClient,back:()->Unit){var data by remember{mutableStateOf<JSONObject?>(null)};var error by remember{mutableStateOf("")};val scope=rememberCoroutineScope();val month=remember{java.time.LocalDate.now().toString().substring(0,7)};LaunchedEffect(Unit){scope.launch{runCatching{api.laporanBulan(month)}.onSuccess{data=it}.onFailure{error=it.message?:"Gagal memuat laporan"}}};LazyColumn(Modifier.fillMaxSize().padding(p),contentPadding=PaddingValues(16.dp,8.dp,16.dp,110.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){item{Header("Laporan Kasir","GET /api/laporan/bulan • $month",back)};if(error.isNotBlank())item{CardText("Error",error)};item{Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(8.dp)){Metric("Omzet",rp(data?.n("omzet","total_omzet","penjualan")?:0L),Modifier.weight(1f));Metric("Transaksi",(data?.n("jumlah_transaksi","total_transaksi","count")?:0L).toString(),Modifier.weight(1f))}};item{CardText("Ringkasan","Data laporan ditampilkan dari response backend, bukan raw JSON.")}}}

@Composable private fun Kasbon(p:PaddingValues,api:ApiClient,back:()->Unit){var data by remember{mutableStateOf<JSONObject?>(null)};var error by remember{mutableStateOf("")};var add by remember{mutableStateOf(false)};val scope=rememberCoroutineScope();fun load()=scope.launch{runCatching{api.kasbon()}.onSuccess{data=it;error=""}.onFailure{error=it.message?:"Gagal memuat kasbon"}};LaunchedEffect(Unit){load()};val rows=data?.a("items","data","kasbon","results").orEmpty();LazyColumn(Modifier.fillMaxSize().padding(p),contentPadding=PaddingValues(16.dp,8.dp,16.dp,110.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){item{Header("Kasbon Pelanggan","GET /api/kasbon",back)};item{Button(Modifier.fillMaxWidth(),onClick={add=true}){Text("Tambah Kasbon")}};if(error.isNotBlank())item{CardText("Error",error)};if(rows.isEmpty()&&error.isBlank())item{CardText("Belum ada kasbon","Server tidak mengembalikan data kasbon.")};items(rows){r->CardText(r.s("nama_pelanggan","pelanggan","nama"),"Sisa: ${rp(r.n("sisa","saldo","nominal"))} • Jatuh tempo: ${r.s("jatuh_tempo","tanggal_jatuh_tempo")}")}};if(add)SimpleJsonDialog("Tambah Kasbon","pelanggan_id","nominal"){body->scope.launch{runCatching{api.createKasbon(body)}.onSuccess{add=false;load()}.onFailure{error=it.message?:"Gagal menyimpan"}}}}

@Composable private fun Payroll(p:PaddingValues,api:ApiClient,back:()->Unit){var data by remember{mutableStateOf<JSONObject?>(null)};var rate by remember{mutableStateOf<JSONObject?>(null)};var error by remember{mutableStateOf("")};val scope=rememberCoroutineScope();LaunchedEffect(Unit){scope.launch{runCatching{api.gaji()}.onSuccess{data=it}.onFailure{error=it.message?:"Gagal memuat gaji"};runCatching{api.gajiRates()}.onSuccess{rate=it}}};LazyColumn(Modifier.fillMaxSize().padding(p),contentPadding=PaddingValues(16.dp,8.dp,16.dp,110.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){item{Header("Gaji Karyawan","GET /api/gaji + /api/gaji/rate",back)};if(error.isNotBlank())item{CardText("Error",error)};item{CardText("Payroll","Data payroll diproses server. Response mentah tidak ditampilkan sebagai JSON.")};item{CardText("Jumlah data",(data?.a("items","data","results")?.size?:0).toString())};item{CardText("Rate",rate?.s("status","message")?:"Rate tersedia dari endpoint resmi.")}}}

@Composable private fun More(p:PaddingValues,open:(Page)->Unit,back:()->Unit,canPayroll:Boolean){LazyColumn(Modifier.fillMaxSize().padding(p),contentPadding=PaddingValues(16.dp,8.dp,16.dp,110.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){item{Header("Lainnya","Semua modul",back)};item{Module("Transaksi","Riwayat dan koreksi transaksi",Icons.Default.ReceiptLong){open(Page.TRANSAKSI)}};item{Module("Stok","Produk dan stok",Icons.Default.Inventory2){open(Page.STOK)}};item{Module("Kategori","Kelola kategori produk",Icons.Default.Category){open(Page.KATEGORI)}};item{Module("Service HP","Tiket servis dan pickup",Icons.Default.Build){open(Page.SERVICE)}};item{Module("Kasbon","Hutang pelanggan",Icons.Default.ReceiptLong){open(Page.KASBON)}};item{Module("Pelanggan","Database pelanggan",Icons.Default.People){open(Page.PELANGGAN)}};item{Module("Pengeluaran","Pengeluaran toko",Icons.Default.Wallet){open(Page.PENGELUARAN)}};if(canPayroll)item{Module("Gaji","Payroll karyawan",Icons.Default.Assessment){open(Page.GAJI)}};item{Module("Pengaturan","Konfigurasi aplikasi",Icons.Default.Settings){open(Page.PENGATURAN)}}}}
@Composable private fun Module(title:String,body:String,icon:androidx.compose.ui.graphics.vector.ImageVector,click:()->Unit){Card(Modifier.fillMaxWidth().clickable(onClick=click),colors=CardDefaults.cardColors(CardColor),shape=RoundedCornerShape(16.dp)){Row(Modifier.padding(16.dp),verticalAlignment=Alignment.CenterVertically){Icon(icon,null,tint=Scheme.primary);Spacer(Modifier.width(14.dp));Column(Modifier.weight(1f)){Text(title,fontWeight=FontWeight.Bold);Text(body,color=Muted)};Icon(Icons.Default.ChevronRight,null,tint=Muted)}}}
@Composable private fun Unsupported(p:PaddingValues,title:String,body:String,back:()->Unit){Column(Modifier.fillMaxSize().padding(p).padding(16.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){Header(title,"Menunggu kontrak backend",back);CardText("Belum tersedia",body);Text("Tidak ada endpoint fiktif yang dipanggil.",color=Muted)}}

@Composable private fun TransactionSheet(api:ApiClient,close:()->Unit){var product by remember{mutableStateOf("")};var qty by remember{mutableStateOf("1")};var method by remember{mutableStateOf("Tunai")};var account by remember{mutableStateOf("")};var customer by remember{mutableStateOf("")};var saving by remember{mutableStateOf(false)};var error by remember{mutableStateOf("")};val scope=rememberCoroutineScope();AlertDialog(onDismissRequest={if(!saving)close()},title={Text("Transaksi Baru")},text={Column(Modifier.verticalScroll(rememberScrollState()),verticalArrangement=Arrangement.spacedBy(8.dp)){Text("POST /api/transaksi • Idempotency-Key otomatis",color=Muted);OutlinedTextField(product,{product=it},label={Text("Produk ID")},singleLine=true,modifier=Modifier.fillMaxWidth());OutlinedTextField(qty,{qty=it},label={Text("Qty")},singleLine=true,modifier=Modifier.fillMaxWidth());OutlinedTextField(method,{method=it},label={Text("Metode Bayar")},singleLine=true,modifier=Modifier.fillMaxWidth());OutlinedTextField(account,{account=it},label={Text("Akun Penerima")},singleLine=true,modifier=Modifier.fillMaxWidth());OutlinedTextField(customer,{customer=it},label={Text("Pelanggan ID")},singleLine=true,modifier=Modifier.fillMaxWidth());if(error.isNotBlank())Text(error,color=Scheme.error)}},confirmButton={Button(enabled=!saving,onClick={scope.launch{saving=true;val items=JSONArray();if(product.isNotBlank())items.put(JSONObject().put("produk_id",product).put("qty",qty.toLongOrNull()?:1));val body=JSONObject().put("items",items).put("metode_bayar",method).put("manual_entry",true);if(account.isNotBlank())body.put("akun_penerima",account);if(customer.isNotBlank())body.put("pelanggan_id",customer);runCatching{api.createTransaksi(body)}.onSuccess{close()}.onFailure{error=it.message?:"Gagal menyimpan transaksi"};saving=false}}){Text(if(saving)"Menyimpan…" else "Simpan")}},dismissButton={TextButton(enabled=!saving,onClick=close){Text("Batal")}})}

@Composable private fun SimpleJsonDialog(title:String,key1:String,key2:String,save:(JSONObject)->Unit){var v1 by remember{mutableStateOf("")};var v2 by remember{mutableStateOf("")};AlertDialog(onDismissRequest={},title={Text(title)},text={Column(verticalArrangement=Arrangement.spacedBy(8.dp)){OutlinedTextField(v1,{v1=it},label={Text(key1)},modifier=Modifier.fillMaxWidth());OutlinedTextField(v2,{v2=it},label={Text(key2)},modifier=Modifier.fillMaxWidth())}},confirmButton={Button(onClick={save(JSONObject().put(key1,v1).put(key2,v2.toLongOrNull()?:0L))}){Text("Simpan")}},dismissButton={TextButton(onClick={}){Text("Batal")}})}
